/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as StopLossRouteImport } from './routes/stop-loss'
import { Route as ApiPublicVeniceTestRouteImport } from './routes/api/public/venice-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StopLossRoute = StopLossRouteImport.update({
  id: '/stop-loss',
  path: '/stop-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVeniceTestRoute = ApiPublicVeniceTestRouteImport.update({
  id: '/api/public/venice-test',
  path: '/api/public/venice-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/stop-loss': typeof StopLossRoute
  '/api/public/venice-test': typeof ApiPublicVeniceTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/stop-loss': typeof StopLossRoute
  '/api/public/venice-test': typeof ApiPublicVeniceTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/stop-loss': typeof StopLossRoute
  '/api/public/venice-test': typeof ApiPublicVeniceTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/stop-loss' | '/api/public/venice-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/stop-loss' | '/api/public/venice-test'
  id: '__root__' | '/' | '/dashboard' | '/stop-loss' | '/api/public/venice-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  StopLossRoute: typeof StopLossRoute
  ApiPublicVeniceTestRoute: typeof ApiPublicVeniceTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop-loss': {
      id: '/stop-loss'
      path: '/stop-loss'
      fullPath: '/stop-loss'
      preLoaderRoute: typeof StopLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/venice-test': {
      id: '/api/public/venice-test'
      path: '/api/public/venice-test'
      fullPath: '/api/public/venice-test'
      preLoaderRoute: typeof ApiPublicVeniceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  StopLossRoute: StopLossRoute,
  ApiPublicVeniceTestRoute: ApiPublicVeniceTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
